export const treatmentList = [
    "Haircuts",
    "Hair Coloring",
    "Hair Styling",
    "Deep Conditioning",
    "Scalp Treatments",
    "Men’s Grooming",
    "Facials",
    "Microdermabrasion",
    "Chemical Peels",
    "Face Masks",
    "Manicures",
    "Pedicures",
    "Nail Enhancements",
    "Waxing",
    "Spray Tans",
    "Massage",
    "Bridal Services",
    "Event Makeup",
    "Home Spa Services",
    "Eyebrow Shaping",
    "Lash Extensions",
    "Body Scrubs",
    "Sunless Tanning",
    "Acne Treatments",
    "Anti-Aging Treatments",
    "Hair Extensions",
  ];
  